name: git-push
author: gendloop
description: 'git-push'
inputs:
# Required
  commit:
    description: 'Commi message'
    required: false
    default: 'chore: update'
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: push
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
          GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global credential.helper store
        echo "machine github.com login ${{ github.actor }} password ${{ inputs.token }}" > ~/.netrc
        git pull
        git add .
        (git commit -m "${{ inputs.commit }}") || true
        (git push) || true
